# kempt configuration: https://github.com/ZacSweers/kempt

[ktfmt]
version = "0.64"

[gjf]
version = "1.35.0"

[license-header]
file = "config/license-header.txt"

[ktfmt.license-header]
excludes = "config/license-header-excludes-kt.txt"

[paths]
exclude = [
  "**/build/**",
  "**/target/**",
  "**/.gradle/**",
  "**/generated/**",
]

[ktfmt.paths]
include = [
  "**/*.kt",
  "**/*.kts",
]

[gjf.paths]
include = ["**/*.java"]

[hook]
mode = "format"
