include(
  ":app",
  ":libraries:auth",
  ":libraries:base-ui",
  ":libraries:appconfig",
  ":libraries:compose-extensions",
  ":libraries:compose-extensions:pull-refresh",
  ":libraries:di",
  ":libraries:di:android",
  ":libraries:gemoji",
  ":libraries:gemoji:db",
  ":libraries:gemoji:generator",
  ":libraries:flowbinding",
  ":libraries:kotlinutil",
  ":libraries:newark",
  ":libraries:retrofitconverters",
  ":libraries:summarizer",
  ":libraries:tooling:spi-multibinds-validator",
  ":libraries:tooling:spi-visualizer",
  ":libraries:util",
  ":service-api",
  ":service-db",
  ":services:designernews",
  ":services:dribbble",
  ":services:github",
  ":services:hackernews",
//    ":services:imgur",
//  ":services:medium",
//    ":services:newsapi",
  ":services:producthunt",
  ":services:reddit",
  ":services:slashdot",
  ":services:unsplash",
  ":services:uplabs",
)