import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val aapt2: String = "3.3.0-alpha13-5013011" // up-to-date

    const val adapter_rxjava2: String = "2.4.0" // up-to-date

    const val androidx_annotation_annotation: String = "1.0.0" // up-to-date

    const val androidx_core_core: String = "1.0.0" // up-to-date

    const val annotations: String = "4.8.0" // up-to-date

    const val apollo_android_support: String = "1.0.0-alpha" // available milestone: "1.0.0-alpha2" 

    const val apollo_gradle_plugin: String = "1.0.0-alpha" // available milestone: "1.0.0-alpha2" 

    const val apollo_http_cache: String = "1.0.0-alpha" // available milestone: "1.0.0-alpha2" 

    const val apollo_runtime: String = "1.0.0-alpha" // available milestone: "1.0.0-alpha2" 

    const val apollo_rx2_support: String = "1.0.0-alpha" // available milestone: "1.0.0-alpha2" 

    const val appcompat: String = "1.0.0" // up-to-date

    const val auto_common: String = "0.10" // up-to-date

    const val auto_service: String = "1.0-rc4" // up-to-date

    const val autodispose: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_android: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_android_archcomponents: String =
            "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_android_archcomponents_ktx: String =
            "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_android_ktx: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_ktx: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_lifecycle: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val autodispose_lifecycle_ktx: String = "1.0.0-RC2" // available milestone: "1.0.0" 

    const val browser: String = "1.0.0" // up-to-date

    const val bugsnag_android: String = "4.6.1" // available milestone: "4.8.2" 

    const val bugsnag_android_gradle_plugin: String = "3.4.1" // available milestone: "3.4.2" 

    const val com_android_tools_build_gradle: String = "3.3.0-alpha13" // up-to-date

    const val com_github_bumptech_glide_compiler: String = "4.8.0" // up-to-date

    const val com_gradle_build_scan_gradle_plugin: String = "1.16" // up-to-date

    const val com_tickaroo_tikxml_annotation: String = "0.8.13" // up-to-date

    const val com_tickaroo_tikxml_core: String = "0.8.13" // up-to-date

    const val constraintlayout: String = "1.1.2" // available milestone: "2.0.0-alpha2" 

    const val converter_htmlescape: String = "0.8.13" // up-to-date

    const val converter_moshi: String = "2.4.0" // up-to-date

    const val core_ktx: String = "1.0.0" // up-to-date

    const val crumb_annotations: String = "0.0.1" // up-to-date

    const val crumb_compiler: String = "0.0.1" // up-to-date

    const val crumb_compiler_api: String = "0.0.1" // up-to-date

    const val dagger: String = "2.16" // up-to-date

    const val dagger_android: String = "2.16" // up-to-date

    const val dagger_android_processor: String = "2.16" // up-to-date

    const val dagger_android_support: String = "2.16" // up-to-date

    const val dagger_compiler: String = "2.16" // up-to-date

    const val dagger_spi: String = "2.16" // up-to-date

    const val drawerlayout: String = "1.0.0" // up-to-date

    const val emoji: String = "1.0.0" // up-to-date

    const val emoji_appcompat: String = "1.0.0" // up-to-date

    const val error_prone_annotations: String = "2.3.1" // available milestone: "2.3.2" 

    const val firebase_config: String = "16.0.1" // up-to-date

    const val firebase_core: String = "16.0.4" // up-to-date

    const val firebase_database: String = "16.0.3" // up-to-date

    const val firebase_perf: String = "16.1.2" // up-to-date

    const val firebase_plugins: String = "1.1.5" // up-to-date

    const val flick: String = "1.3.0" // available milestone: "1.4.0" 

    const val flipper: String = "0.7.1" // available milestone: "0.9.0" 

    const val fragment: String = "1.0.0" // up-to-date

    const val fragment_ktx: String = "1.0.0" // up-to-date

    const val gesture_views: String = "2.2.0" // available milestone: "2.5.2" 

    const val glide: String = "4.8.0" // up-to-date

    const val inboxrecyclerview: String = "1.0.0-SNAPSHOT" // available milestone: "1.0.0-beta3" 

    const val inspector: String = "0.3.0" // up-to-date

    const val inspector_android_compiler_extension: String = "0.3.0" // up-to-date

    const val inspector_autovalue_compiler_extension: String = "0.3.0" // up-to-date

    const val inspector_compiler: String = "0.3.0" // up-to-date

    const val inspector_factory_compiler: String = "0.3.0" // up-to-date

    const val inspector_factory_compiler_annotations: String = "0.3.0" // up-to-date

    const val inspector_nullability_compiler_extension: String = "0.3.0" // up-to-date

    const val javapoet: String = "1.11.1" // up-to-date

    const val javax_annotation: String = "10.0-b28" // up-to-date

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.4" // exceed the version found: 0.2.3

    const val jsoup: String = "1.11.3" // up-to-date

    const val jsr305: String = "3.0.2" // up-to-date

    const val junit: String = "4.12" // up-to-date

    const val kotlin_annotation_processing_gradle: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_gradle_plugin: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_metadata: String = "1.4.0" // up-to-date

    const val kotlin_noarg: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_scripting_compiler_embeddable: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_stdlib: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_stdlib_jdk7: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_stdlib_jdk8: String = "1.3.0-rc-146" // up-to-date

    const val kotlinpoet: String = "1.0.0-RC1" // up-to-date

    const val lazythreetenbp: String = "0.4.0" // up-to-date

    const val leakcanary_android: String = "1.6.1" // up-to-date

    const val leakcanary_android_no_op: String = "1.6.1" // up-to-date

    const val library: String = "1.1.0" // up-to-date

    const val library_no_op: String = "1.1.0" // up-to-date

    const val lifecycle_compiler: String = "2.0.0" // up-to-date

    const val lifecycle_extensions: String = "2.0.0" // up-to-date

    const val lint_gradle: String = "26.3.0-alpha13" // up-to-date

    const val logging_interceptor: String = "3.11.0" // up-to-date

    const val lottie: String = "2.6.1" // available milestone: "2.8.0" 

    const val madge: String = "1.1.4" // up-to-date

    const val material: String = "1.0.0" // up-to-date

    const val moshi: String = "1.7.0" // up-to-date

    const val moshi_kotlin_codegen: String = "1.7.0" // up-to-date

    const val moshi_lazy_adapters: String = "2.2" // up-to-date

    const val okhttp: String = "3.11.0" // up-to-date

    const val okhttp3_integration: String = "4.8.0" // up-to-date

    const val okio: String = "2.0.0" // available milestone: "2.1.0" 

    const val palette: String = "1.0.0" // up-to-date

    const val palette_ktx: String = "1.0.0" // up-to-date

    const val play_publisher: String = "1.2.2" // available milestone: "2.0.0-beta1" 

    const val preference: String = "1.0.0" // up-to-date

    const val preference_ktx: String = "1.0.0" // up-to-date

    const val process_phoenix: String = "2.0.0" // up-to-date

    const val processor: String = "0.8.13" // up-to-date

    const val psync: String = "2.0.0-20171017.111936-4" 
            /* Could not find any version that matches io.sweers.psync:psync:+.
            Versions rejected by component selection rules: 2.0.0-SNAPSHOT
            Searched in the following locations:
              - file:/Users/jmfayard/.gradle/caches/4.10.2/embedded-kotlin-repo-1.2.61-2/repo/io/sweers/psync/psync/ 
            .... */

    const val recyclerview_animators: String = "2.3.0" // up-to-date

    const val recyclerview_integration: String = "4.8.0" // up-to-date

    const val retrofit: String = "2.4.0" // up-to-date

    const val retrofit_converter: String = "0.8.13" // up-to-date

    const val retrofit_mock: String = "2.4.0" // up-to-date

    const val room_compiler: String = "2.1.0-alpha01" // up-to-date

    const val room_runtime: String = "2.1.0-alpha01" // up-to-date

    const val room_rxjava2: String = "2.1.0-alpha01" // up-to-date

    const val rx_preferences: String = "2.0.0" // up-to-date

    const val rxandroid: String = "2.1.0" // up-to-date

    const val rxbinding_design_kotlin: String = "2.2.0" // up-to-date

    const val rxbinding_kotlin: String = "2.2.0" // up-to-date

    const val rxbinding_support_v4_kotlin: String = "2.2.0" // up-to-date

    const val rxjava: String = "2.2.2" // up-to-date

    const val rxrelay: String = "2.0.0" // available milestone: "2.1.0" 

    const val scalpel: String = "1.1.2" // up-to-date

    const val stetho: String = "1.5.0" // up-to-date

    const val stetho_okhttp3: String = "1.5.0" // up-to-date

    const val stetho_timber: String = "1.5.0" // up-to-date

    const val support_annotations: String = "28.0.0" // up-to-date

    const val swiperefreshlayout: String = "1.0.0" // up-to-date

    const val taptargetview: String = "1.12.0" // up-to-date

    const val telescope: String = "2.1.0" // up-to-date

    const val timber: String = "4.7.1" // up-to-date

    const val truth: String = "0.42" // up-to-date

    const val unbescape: String = "1.1.6.RELEASE" // up-to-date

    const val viewpager: String = "1.0.0" // up-to-date

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181015235836+0000"

        const val releaseCandidate: String = ""
    }
}
